+define+ABV_ON
./src/main/verilog/vscale_core.v
./src/main/verilog/vscale_hasti_bridge.v
./src/main/verilog/vscale_pipeline.v 
./src/main/verilog/vscale_ctrl.v
./src/main/verilog/vscale_regfile.v 
./src/main/verilog/vscale_src_a_mux.v
./src/main/verilog/vscale_src_b_mux.v 
./src/main/verilog/vscale_imm_gen.v
./src/main/verilog/vscale_alu.v 
./src/main/verilog/vscale_mul_div.v
./src/main/verilog/vscale_csr_file.v 
./src/main/verilog/vscale_PC_mux.v
./src/main/verilog/vscale_dp_hasti_sram.v
./src/main/verilog/vscale_ctrl_constants.vh
./src/main/verilog/rv32_opcodes.vh 
./src/main/verilog/vscale_alu_ops.vh
./src/main/verilog/vscale_md_constants.vh
./src/main/verilog/vscale_hasti_constants.vh
./src/main/verilog/vscale_csr_addr_map.vh
./src/main/verilog/vscale_arbiter.v
